# Generated by Django 5.2.17 on 2026-08-28 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateways', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('device_id', models.CharField(max_length=120)),
                ('device_token_hash', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('maintenance', 'Maintenance'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30)),
                ('protocol', models.CharField(choices=[('MQTT', 'MQTT'), ('HTTP', 'HTTP'), ('Modbus TCP', 'Modbus TCP'), ('Modbus RTU', 'Modbus RTU'), ('OPC-UA', 'OPC-UA'), ('Custom', 'Custom')], db_index=True, default='MQTT', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gateways.gateway')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='devices_dev_organiz_c0273e_idx'), models.Index(fields=['organization', 'protocol'], name='devices_dev_organiz_8ea9e8_idx')],
                'unique_together': {('organization', 'device_id')},
            },
        ),
    ]
